

# Growout total table
# Table with weights to calculate total from the internal and external groups
stat_subgroups_total_weights_growout <- tibble::tribble( # growout_total_table
  #####
  ~stat_subgroup, ~stat_subgroup_add, ~weight, 
  "ext", "total", 1,
  "int", "total", 1)
#####

# Growout int/ext table
# Table with weights to calculate internal and external groups from original subgroups
stat_subgroups_int_ext_weights_growout <- tibble::tribble( # growout_int_ext_table
  #####
  ~stat_subgroup, ~stat_subgroup_add, ~weight, 
  "su1.1",  "ext", 1, 
  "su1.2",  "ext", 1, 
  "su1.3",  "ext", 1, 
  "su1.4",  "ext", 1, 
  "su1.5",  "ext", 1, 
  "su1.6",  "ext", 1, 
  "su1.7",  "ext", 1, 
  "su1.8",  "int", 1, 
  "su1.9",  "int", 1, 
  "su1.10", "int", 1, 
  "su1.11", "int", 1, 
  "su1.12", "int", 1, 
  "su1.13", "int", 1, 
  "su1.14", "int", 1, 
  "su1.15", "int", 1)
#####

# Growout subgroup table
# Subgroups with grouping and titles in Norwegian and English
stat_subgroups_growout <- tibble::tribble( # growout_subgroup_table
  #####
  ~stat_subgroup, ~stat_group, ~stat_title_en, ~stat_title_nw, 
  "su1.1",  "external", "1) Location of the farm", "1) Plassering av lokaliteten",
  "su1.2",  "external", "2) Introduction of live fish", "2)",
  "su1.3",  "external", "3) Feed supply", "3)",
  "su1.4",  "external", "4) Biovectors", "4)  Biovektorer",
  "su1.5",  "external", "5) Personnel and visitors", "5)",
  "su1.6",  "external", "6) Use of divers", "6)",
  "su1.7",  "external", "7) Equipment and vehicles for transport of live fish, feed and waste", "7)",
  "ext",    "external", "Subtotal external Biosecurity", "",
  "su1.8",  "internal", "8) Vaccination", "8)",
  "su1.9",  "internal", "9) Disease management", "9)",
  "su1.10", "internal", "10) Rearing management", "10)",
  "su1.11", "internal", "11) Feed management", "11)",
  "su1.12", "internal", "12) Waste management", "12)",
  "su1.13", "internal", "13) Harvesting", "13)",
  "su1.14", "internal", "14) Equipment, cleaning and disinfection onsite", "14)",
  "su1.15", "internal", "15) Biosecurity program and record keeping", "15)",
  "int",    "internal", "Subtotal internal Biosecurity", "",
  "total",  "total",    "Overall biosecurity", "")
#####

# Growout question table
# Table with scoring questions + functions and their weights within the subgroup.
# Score functions must score between 0 and 1
stat_questions_growout <- tibble::tribble( # growout_question_table
  ~stat_question_nw, ~stat_question_en,
  ~stat_subgroup, ~stat_qn, ~weight, ~score_func, ~answer_func, 
  # EXTERNAL BIOSECURITY
  #####
  # 1) LOCATION OF THE FARM
  #####
  "Hvor er lokaliteten plassert?", "",
  "su1.1",  "q0", 1, function(.data) { ifelse(.data$`2.9`=="På land",1,0) }, function(.data) { .data$`2.9` },  
  "Hvor mange aktive lokaliteter med laksefiskprosduksjon finnes innenfor en radius på 10 km fra denne lokaliteten? [Settefiskanlegg]", "",
  "su1.1",  "q1", 1, function(.data) { ifelse(.data$`2.10.1`=="Ingen",1,0) }, function(.data) { .data$`2.10.1` },  
  "Hvor mange aktive lokaliteter med laksefiskprosduksjon finnes innenfor en radius på 10 km fra denne lokaliteten? [Postsmolt]", "",
  "su1.1",  "q2", 1, function(.data) { ifelse(.data$`2.10.2` =="Ingen",1,0) }, function(.data) { .data$`2.10.2` },  
  "Hvor mange aktive lokaliteter med laksefiskprosduksjon finnes innenfor en radius på 10 km fra denne lokaliteten? [Matfisk]", "",
  "su1.1",  "q3", 1, function(.data) { ifelse(.data$`2.10.3` =="Ingen",1,0) }, function(.data) { .data$`2.10.3` },  
  "Hvor mange aktive lokaliteter med laksefiskprosduksjon finnes innenfor en radius på 10 km fra denne lokaliteten? [Slakteri og/eller videreforedlingsbedrift]", "",
  "su1.1",  "q4", 1, function(.data) { ifelse(.data$`2.10.4` =="Ingen",1,0) }, function(.data) { .data$`2.10.4` },  
  "Finnes det gjerder, porter eller skilt som advarer personer og kjøretøy mot adgang til anlegget uten tillatelse?", "",
  "su1.1",  "q5", 1, function(.data) { ifelse(.data$`8.8`=="Ja",1,ifelse(.data$`8.8`=="Ikke aktuelt, da lokaliteten ikke er på land",1,0)) }, function(.data) { .data$`8.8` },  
  #####
  # 2) Introduction of live fish
  #####
  "Er det egen protokol (SOP) for inntak av fisk?", "",
  "su1.2",  "q6",  1,  function(.data) { ifelse(.data$`5.1`=="Ja",1,0) }, function(.data) { .data$`5.1` },
  "Hvor mange forsendelser med smolt har vært tatt inn på lokaliteten i løpet av de siste 12 måneder?-Fra eget selskap", "",
  "su1.2",  "q7",  1,  function(.data) { ifelse(.data$`5.2.1`=="Ingen",1,0) }, function(.data) { .data$`5.2.1` },
  "Hvor mange forsendelser med smolt har vært tatt inn på lokaliteten i løpet av de siste 12 måneder?-Fra ekternt selskap", "",
  "su1.2",  "q8",  1,  function(.data) { ifelse(.data$`5.2.2`=="Ingen",1,0) }, function(.data) { .data$`5.2.2` },
  "Hvor mange forsendelser med postsmolt har vært tatt inn på lokaliteten i løpet av de siste 12 måneder? Fra eget selskap", "",
  "su1.2",  "q9",  1,  function(.data) { ifelse(.data$`5.3.1`=="Ingen",1,0) }, function(.data) { .data$`5.3.1` },
  "Hvor mange forsendelser med postsmolt har vært tatt inn på lokaliteten i løpet av de siste 12 måneder?Fra ekternt selskap", "",
  "su1.2",  "q10", 1,  function(.data) { ifelse(.data$`5.3.2`=="Ingen",1,0) }, function(.data) { .data$`5.3.2` },
  "Krav ved inntak av fisk fra eget selskap-Vi krever helseattest/rapporter som dokumenterer fravær av viktige smittsomme agens i settefiskpopulasjonen", "",
  "su1.2",  "q11", 1,  function(.data) { ifelse(.data$`5.4.1`=="Ja",1,0) }, function(.data) { .data$`5.4.1` },
  "Krav ved inntak av fisk fra eget selskap-Vi krever resultater fra diagnostiske undersøkelser som gjelder viktige smittsomme agens", "",
  "su1.2",  "q12", 1,  function(.data) { ifelse(.data$`5.4.2`=="Ja",1,0) }, function(.data) { .data$`5.4.2` },
  "Krav ved inntak av fisk fra eget selskap-Vi krever oversikt over gjennomførte smittereduserende tiltak", "",
  "su1.2",  "q13", 1,  function(.data) { ifelse(.data$`5.4.3`=="Ja",1,0) }, function(.data) { .data$`5.4.3` },
  "Krav ved inntak av fisk fra eget selskap-Vi undersøker fisk ved ankomst", "",
  "su1.2",  "q14", 1,  function(.data) { ifelse(.data$`5.4.4`=="Ja",1,0) }, function(.data) { .data$`5.4.4` },
  "Krav ved inntak av fisk fra eget selskap-Vi undersøker fisk og opprinnelsesanlegg før bestilling", "",
  "su1.2",  "q15", 1,  function(.data) { ifelse(.data$`5.4.5`=="Ja",1,0) }, function(.data) { .data$`5.4.5` },
  "Krav ved inntak av fisk fra ekternt selskap-Vi krever helseattest/rapporter som dokumenterer fravær av viktige smittsomme agens i settefiskpopulasjonen", "",
  "su1.2",  "q16", 1,  function(.data) { ifelse(.data$`5.5.1`=="Ja",1,0) }, function(.data) { .data$`5.5.1` },
  "Krav ved inntak av fisk fra ekternt selskap-Vi krever resultater fra diagnostiske undersøkelser som gjelder viktige smittsomme agens", "",
  "su1.2",  "q17", 1,  function(.data) { ifelse(.data$`5.5.2`=="Ja",1,0) }, function(.data) { .data$`5.5.2` },
  "Krav ved inntak av fisk fra ekternt selskap-Vi krever oversikt over gjennomførte smittereduserende tiltak", "",
  "su1.2",  "q18", 1,  function(.data) { ifelse(.data$`5.5.3`=="Ja",1,0) }, function(.data) { .data$`5.5.3` },
  "Krav ved inntak av fisk fra ekternt selskap-Vi undersøker fisk ved ankomst", "",
  "su1.2",  "q19", 1,  function(.data) { ifelse(.data$`5.5.4`=="Ja",1,0) }, function(.data) { .data$`5.5.4` },
  "Krav ved inntak av fisk fra ekternt selskap-Vi undersøker fisk og opprinnelsesanlegg før bestilling", "",
  "su1.2",  "q20", 1,  function(.data) { ifelse(.data$`5.5.5`=="Ja",1,0) }, function(.data) { .data$`5.5.5` },
  "Skjer lossing av fisk i et eget område og / eller i avstand fra eksisterende fisk på lokaliteten?", "",
  "su1.2",  "q21", 1,  function(.data) { ifelse(.data$`5.6`=="Ja",1,0) }, function(.data) { .data$`5.6` },
  "Kreves det at fisk som leveres til lokaliteten, skal settes i karantene ved ankomst?", "",
  "su1.2",  "q22", 1,  function(.data) { ifelse(.data$`5.7`=="Ja",1,0) }, function(.data) { .data$`5.7` },
  "Har anlegget egne områder/innredninger som brukes til karantene?", "",
  "su1.2",  "q23", 1,  function(.data) { ifelse(.data$`5.8`=="Ja",1,0) }, function(.data) { .data$`5.8` },
  "Gjennomføres nedvask av karanteneområdene etter hver gang de har vært i bruk?", "",
  "su1.2",  "q24", 1,  function(.data) { ifelse(.data$`5.9`=="Ja",1,0) }, function(.data) { .data$`5.9` },
  "Inkluderes ny fisk i fiskegrupper som er i anlegget fra før (dvs. i samme not sjøanlegg eller samme avdeling, settefiskanlegg) i løpet av en produksjonssyklus", "",
  "su1.2",  "q25", 1,  function(.data) { ifelse(.data$`8.9`=="Ja",1,0) }, function(.data) { .data$`8.9` },
  ##### 
  # 3) FEED SUPPLY
  #####
  "Benyttes frosset fisk, fiskeavfall eller annet rått fôr?", "",
  "su1.3",  "q26", 1,  function(.data) { ifelse(.data$`7.6`=="Nei",1,0) }, function(.data) { .data$`7.6` },
  "Hvor ofte undersøkes frosset fisk, fiskeavfall eller levende fôr, for forekomst av patogener (feks bakterier og/eller virus)?", "",
  "su1.3",  "q27", 1,  function(.data) { ifelse(.data$`7.7`=="Alle nye batcher",1, ifelse(.data$`7.7`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`7.7` },
  ##### 
  # 4) BIOVECTORS
  #####
  "Er det satt i verk tiltak for å forhindre at predatorer og/eller åtseletere kommer inn på denne lokaliteten?", "",
  "su1.4",  "q28", 1,  function(.data) { ifelse(.data$`10.1`=="Ja",1,0) }, function(.data) { .data$`10.1` },
  "Holdes fiskeavfall (eksempelvis død fisk, slaktet fisk, rester av fisk uegnet til menneskemat) unna predatorer/åtseletere?", "",
  "su1.4",  "q29", 1,  function(.data) { ifelse(.data$`10.2`=="Ja",1,0) }, function(.data) { .data$`10.2` },
  "Holdes det oversikt over følgende:Tiltak som er satt i verk for å hindre predatorer", "",
  "su1.4",  "q30", 1,  function(.data) { ifelse(.data$`10.3.1`=="Ja",1,0) }, function(.data) { .data$`10.3.1` },
  "Holdes det oversikt over følgende:Inspeksjoner av kontrolltiltak for å hindre predatorer", "",
  "su1.4",  "q31", 1,  function(.data) { ifelse(.data$`10.3.2`=="Ja",1,0) }, function(.data) { .data$`10.3.2` },
  "Holdes det oversikt over følgende:Synsobservasjoner av relevante predatorer", "",
  "su1.4",  "q32", 1,  function(.data) { ifelse(.data$`10.3.3`=="Ja",1,0) }, function(.data) { .data$`10.3.3` },
  "Holdes det oversikt over følgende:Tap på grunn av predatorer", "",
  "su1.4",  "q33", 1,  function(.data) { ifelse(.data$`10.3.4`=="Ja",1,0) }, function(.data) { .data$`10.3.4` },
  ##### 
  # 5) PERSONNEL AND VISITORS
  #####
  "Hvis et eksternt transportkjøretøy (bil, båt, etc.) benyttes, kan transportpersonalet bevege seg fritt på lokaliteten mens transporten pågår?", "",
  "su1.5",  "q34", 1,  function(.data) { ifelse(.data$`9.12`=="Nei",1,ifelse(.data$`9.12`=="Ikke aktuelt, fordi det ikke transporteres fisk til og fra denne lokaliteten",1,0)) }, function(.data) { .data$`9.12` },
  "Besøker noen av medarbeiderne på denne lokaliteten andre lokaliteter regelmessig?", "",
  "su1.5",  "q35", 1,  function(.data) { ifelse(.data$`11.1`=="Nei",1,0) }, function(.data) { .data$`11.1` },
  "Har personalet på lokaliteten tilgang til desinfeksjonsstasjoner?", "",
  "su1.5",  "q36", 1,  function(.data) { ifelse(.data$`11.2`=="Ja",1,0) }, function(.data) { .data$`11.2` },
  "Hvor er desinfeksjonsstasjonene plassert? Ved hovedinngangen(e)", "",
  "su1.5",  "q37", 1,  function(.data) { ifelse(.data$`11.3.1`=="Ja",1,0) }, function(.data) { .data$`11.3.1` },
  "Hvor er desinfeksjonsstasjonene plassert? Ved hovedutgangen(e)", "",
  "su1.5",  "q38", 1,  function(.data) { ifelse(.data$`11.3.2`=="Ja",1,0) }, function(.data) { .data$`11.3.2` },
  "Hvor er desinfeksjonsstasjonene plassert? Ved inngang til områder der fisk produseres", "",
  "su1.5",  "q39", 1,  function(.data) { ifelse(.data$`11.3.3`=="Ja",1,0) }, function(.data) { .data$`11.3.3` },
  "Hvor er desinfeksjonsstasjonene plassert? Ved utgang fra områder der fisk produseres", "",
  "su1.5",  "q40", 1,  function(.data) { ifelse(.data$`11.3.4`=="Ja",1,0) }, function(.data) { .data$`11.3.4` },
  "Hvor er desinfeksjonsstasjonene plassert? Det finnes ingen desinfeksjons-stasjoner", "",
  "su1.5",  "q41", 1,  function(.data) { ifelse(.data$`11.3.5`=="Nei",1,0) }, function(.data) { .data$`11.3.5` },
  "Hva er tilgjengelig på desinfeksjons-stasjonene?", "",
  "su1.5",  "q42", 1,  function(.data) { ifelse(.data$`11.4.1`=="Ja",1,0) }, function(.data) { .data$`11.4.1` },
  "Hva er tilgjengelig på desinfeksjons-stasjonene?", "",
  "su1.5",  "q43", 1,  function(.data) { ifelse(.data$`11.4.2`=="Ja",1,0) }, function(.data) { .data$`11.4.2` },
  "Hva er tilgjengelig på desinfeksjons-stasjonene?", "",
  "su1.5",  "q44", 1,  function(.data) { ifelse(.data$`11.4.3`=="Ja",1,0) }, function(.data) { .data$`11.4.3` },
  # "Hva er tilgjengelig på desinfeksjons-stasjonene?", "", # Removed
  # "su1.5",  "q45", 1,  function(.data) { 1 }, 
  "Adgangskontroll: Kreves det at besøkende må melde fra til anleggets personale ved ankomst?", "",
  "su1.5",  "q46", 1,  function(.data) { ifelse(.data$`12.1`=="Ja",1,ifelse(.data$`12.1`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.1` },
  "Kreves det at besøkende følger anleggets biosikkerhets-krav?", "",
  "su1.5",  "q47", 1,  function(.data) { ifelse(.data$`12.2`=="Ja",1,ifelse(.data$`12.2`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.2` },
  "Er besøkende og trafikken på anlegget begrenset til det som er nødvendig for å opprettholde driften?", "",
  "su1.5",  "q48", 1,  function(.data) { ifelse(.data$`12.3`=="Ja",1,ifelse(.data$`12.3`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.3` },
  "Oppholder gjester seg alltid sammen med personalet på lokaliteten, mens de er på besøk?", "",
  "su1.5",  "q49", 1,  function(.data) { ifelse(.data$`12.4`=="Ja",1,ifelse(.data$`12.4`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.4` },
  "Er det et krav at besøkende må være i selskap med anleggets personale, for å kunne oppholde seg i produksjonsområder?", "",
  "su1.5",  "q50", 1,  function(.data) { ifelse(.data$`12.5`=="Ja",1,ifelse(.data$`12.5`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.5` },
  "Er det forbudt for besøkende å være i nærkontakt med, eller håndtere fisk (med mindre det er nødvendig for fiskens helse)?", "",
  "su1.5",  "q51", 1,  function(.data) { ifelse(.data$`12.6`=="Ja",1,ifelse(.data$`12.6`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.6` },
  "Må besøkende ha på seg beskyttelses-bekledning (feks overall/kjeledress, forkle, støvler)?", "",
  "su1.5",  "q52", 1,  function(.data) { ifelse(.data$`12.7`=="Ja",1,ifelse(.data$`12.7`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.7` },
  "Må besøkende signere dokumentasjon som bekrefter at de ikke har besøkt andre oppdrettslokaliteter i forkant av besøket på anlegget, eller alternativt oppgi detaljer knyttet til alle tidligere besøk?", "",
  "su1.5",  "q53", 1,  function(.data) { ifelse(.data$`12.8`=="Ja",1,ifelse(.data$`12.8`=="Besøkende har ikke adgang",1,0)) }, function(.data) { .data$`12.8` },
  ##### 
  # 6) USE OF DIVERS
  #####
  "Hvor ofte benyttes dykkere på dette lokalitet?", "",
  "su1.6",  "q54", 1,  function(.data) { ifelse(.data$`13.1`=="Vi benytter ikke dykkere",1,0) }, function(.data) { .data$`13.1` },
  "Benytter lokaliteten egne dykkere, som bare benyttes på denne lokaliteten?", "",
  "su1.6",  "q55", 1,  function(.data) { ifelse(.data$`13.2`=="Ja",1,ifelse(.data$`13.2`=="Vi benytter ikke dykkere",1,0)) }, function(.data) { .data$`13.2` },
  "Hvis dykkere også dykker på andre lokaliteter, benytter de utstyr som kun brukes på denne lokaliteten?", "",
  "su1.6",  "q56", 1,  function(.data) { ifelse(.data$`13.3`=="Ja",1,ifelse(.data$`13.3`=="Vi benytter ikke dykkere",1,0)) }, function(.data) { .data$`13.3` },
  "Hvis dykkere også dykker på andre lokaliteter, blir det krevet og kontrollert at utstyret deres er vasket og desinfisert?", "",
  "su1.6",  "q57", 1,  function(.data) { ifelse(.data$`13.4`=="Ja",1,ifelse(.data$`13.4`=="Vi benytter ikke dykkere",1,0)) }, function(.data) { .data$`13.4` },
  "Har anlegget desinfeksjons-prosedyrer for dykkeutstyr?", "",
  "su1.6",  "q58", 1,  function(.data) { ifelse(.data$`13.5`=="Ja",1,ifelse(.data$`13.5`=="Vi benytter ikke dykkere",1,0)) }, function(.data) { .data$`13.5` },
  ##### 
  # 7) EQUIPMENT AND VEHICLES FOR TRANSPORT OF LIVE FISH, FEED AND WASTE
  #####
  "Hvor ofte i gjennomsnitt kommer det transportfartøy til denne lokaliteten i produksjonseyklusen?", "",
  "su1.7",  "q59", 1,  function(.data) { ifelse(.data$`2.11.1`=="Månedlig",0.5,ifelse(.data$`2.11.1`=="Aldri",1,0)) }, function(.data) { .data$`2.11.1` }, 
  "Hvor ofte i gjennomsnitt kommer det transportfartøy til denne lokaliteten i produksjonseyklusen?", "",
  "su1.7",  "q60", 1,  function(.data) { ifelse(.data$`2.11.2`=="Månedlig",0.5,ifelse(.data$`2.11.2`=="Aldri",1,0)) }, function(.data) { .data$`2.11.2` }, 
  "Hvor ofte i gjennomsnitt kommer det transportfartøy til denne lokaliteten i produksjonseyklusen?", "",
  "su1.7",  "q61", 1,  function(.data) { ifelse(.data$`2.11.3`=="Månedlig",0.5,ifelse(.data$`2.11.3`=="Aldri",1,0)) }, function(.data) { .data$`2.11.3` }, 
  "Brukes samme innredning og utstyr både til ny fisk og fisk som er i anlegget fra før?", "",
  "su1.7",  "q62", 1,  function(.data) { ifelse(.data$`5.10`=="Nei",1,0) }, function(.data) { .data$`5.10` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Nøter", "",
  "su1.7",  "q63", 1,  function(.data) { ifelse(.data$`9.1.1`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.1`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.1`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.1` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Håver", "",
  "su1.7",  "q64", 1,  function(.data) { ifelse(.data$`9.1.2`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.2`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.2`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.2` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Sorteringsutstyr", "",
  "su1.7",  "q65", 1,  function(.data) { ifelse(.data$`9.1.3`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.3`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.3`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.3` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Pumper", "",
  "su1.7",  "q66", 1,  function(.data) { ifelse(.data$`9.1.4`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.4`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.4`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.4` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Vaksinasjonsutstyr", "",
  "su1.7",  "q67", 1,  function(.data) { ifelse(.data$`9.1.5`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.5`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.5`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.5` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Presenninger", "",
  "su1.7",  "q68", 1,  function(.data) { ifelse(.data$`9.1.6`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.6`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.6`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.6` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Lastebil", "",
  "su1.7",  "q69", 1,  function(.data) { ifelse(.data$`9.1.7`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.7`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.7`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.7` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Brønnbåt", "",
  "su1.7",  "q70", 1,  function(.data) { ifelse(.data$`9.1.8`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.8`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.8`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.8` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Fòringsutstyr", "",
  "su1.7",  "q71", 1,  function(.data) { ifelse(.data$`9.1.9`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.9`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.9`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.9` }, 
  "Hvilke restriksjoner er innført for bruk/sambruk av utstyr og kjøretøy mellom lokaliteter eller mellom avdelinger? Flytende utstyr som båter, raftingbåter ol", "",
  "su1.7",  "q72", 1,  function(.data) { ifelse(.data$`9.1.10`=="Eies og benyttes bare på denne lokaliteten",1,ifelse(.data$`9.1.10`=="Ikke benyttet på denne lokaliteten",1,ifelse(.data$`9.1.10`=="Fellesbruk bare med andre lokaliteter eid av samme selskap",0.5,0))) }, function(.data) { .data$`9.1.10` }, 
  "Blir utstyr som benyttes felles, vasket og desinfisert før det benyttes på ANDRE lokaliteter/avdelinger?", "",
  "su1.7",  "q73", 1,  function(.data) { ifelse(.data$`9.2`=="Ja",1,ifelse(.data$`9.2`=="Vi har ikke felles bruk med andre lokaliteter",1,0)) }, function(.data) { .data$`9.2` }, 
  "Blir transportkjøretøy (bil, båt, etc.) kontrollert ved ankomst?", "",
  "su1.7",  "q74", 1,  function(.data) { ifelse(.data$`9.8`=="Ja",1,0) }, function(.data) { .data$`9.8` }, 
  "Hvilke transportkjøretøy (bil, båt, etc.) benyttes for transport av produkter til denne lokaliteten? Fisk", "",
  "su1.7",  "q75", 1,  function(.data) { ifelse(.data$`9.9.2`=="Transportkjøretøy som bare benyttes på denne lokaliteten",1,ifelse(.data$`9.9.2`=="Ikke aktuelt",1,ifelse(.data$`9.9.2`=="Transportkjøretøy som er felles med andre lokaliteter i samme selskap",0.5,0))) }, function(.data) { .data$`9.9.2` }, 
  "Hvilke transportkjøretøy (bil, båt, etc.) benyttes for transport av produkter til denne lokaliteten? Fôr", "",
  "su1.7",  "q76", 1,  function(.data) { ifelse(.data$`9.9.3`=="Transportkjøretøy som bare benyttes på denne lokaliteten",1,ifelse(.data$`9.9.3`=="Ikke aktuelt",1,ifelse(.data$`9.9.3`=="Transportkjøretøy som er felles med andre lokaliteter i samme selskap",0.5,0))) }, function(.data) { .data$`9.9.3` }, 
  "Hvilke transportkjøretøy (bil, båt, etc.) benyttes for transport av produkter til denne lokaliteten? Avfall", "",
  "su1.7",  "q77", 1,  function(.data) { ifelse(.data$`9.9.4`=="Transportkjøretøy som bare benyttes på denne lokaliteten",1,ifelse(.data$`9.9.4`=="Ikke aktuelt",1,ifelse(.data$`9.9.4`=="Transportkjøretøy som er felles med andre lokaliteter i samme selskap",0.5,0))) }, function(.data) { .data$`9.9.4` }, 
  "Hvis eget transportkjøretøy (bil, båt, etc.) benyttes, hvordan gjennomføres rengjøring og desinfeksjon av kjøretøyet? Fisk", "",
  "su1.7",  "q78", 1,  function(.data) { ifelse(.data$`9.10.2`=="Vi sjekker og signerer OK rengjøring og desinfeksjonsprotokoller, før lasting",1,ifelse(.data$`9.10.2`=="Vi utfører selv rengjøring og desinfeksjon på lokaliteten, før lasting",1,ifelse(.data$`9.10.2`=="Ikke aktuelt, da vi ikke transporterer dette til og fra lokaliteten",1,0))) }, function(.data) { .data$`9.10.2` }, 
  "Hvis eget transportkjøretøy (bil, båt, etc.) benyttes, hvordan gjennomføres rengjøring og desinfeksjon av kjøretøyet? Fòr", "",
  "su1.7",  "q79", 1,  function(.data) { ifelse(.data$`9.10.3`=="Vi sjekker og signerer OK rengjøring og desinfeksjonsprotokoller, før lasting",1,ifelse(.data$`9.10.3`=="Vi utfører selv rengjøring og desinfeksjon på lokaliteten, før lasting",1,ifelse(.data$`9.10.3`=="Ikke aktuelt, da vi ikke transporterer dette til og fra lokaliteten",1,0))) }, function(.data) { .data$`9.10.3` }, 
  "Hvis eget transportkjøretøy (bil, båt, etc.) benyttes, hvordan gjennomføres rengjøring og desinfeksjon av kjøretøyet? Avfall", "",
  "su1.7",  "q80", 1,  function(.data) { ifelse(.data$`9.10.4`=="Vi sjekker og signerer OK rengjøring og desinfeksjonsprotokoller, før lasting",1,ifelse(.data$`9.10.4`=="Vi utfører selv rengjøring og desinfeksjon på lokaliteten, før lasting",1,ifelse(.data$`9.10.4`=="Ikke aktuelt, da vi ikke transporterer dette til og fra lokaliteten",1,0))) }, function(.data) { .data$`9.10.4` }, 
  "Hvis ekstern transportkjøretøy (bil, båt, etc.) benyttes, hvilken dokumentasjon må legges frem før ankomst?", "",
  "su1.7",  "q81", 1,  function(.data) { ifelse(.data$`9.11.1`=="Ja",1/4,0) }, function(.data) { .data$`9.11.1` }, 
  "Hvis ekstern transportkjøretøy (bil, båt, etc.) benyttes, hvilken dokumentasjon må legges frem før ankomst?", "",
  "su1.7",  "q82", 1,  function(.data) { ifelse(.data$`9.11.2`=="Ja",1/4,0) }, function(.data) { .data$`9.11.2` }, 
  "Hvis ekstern transportkjøretøy (bil, båt, etc.) benyttes, hvilken dokumentasjon må legges frem før ankomst?", "",
  "su1.7",  "q83", 1,  function(.data) { ifelse(.data$`9.11.3`=="Ja",1/4,0) }, function(.data) { .data$`9.11.3` }, 
  "Hvis ekstern transportkjøretøy (bil, båt, etc.) benyttes, hvilken dokumentasjon må legges frem før ankomst?", "",
  "su1.7",  "q84", 1,  function(.data) { ifelse(.data$`9.11.4`=="Ja",1/4,0) }, function(.data) { .data$`9.11.4` }, 
  "Hvis ekstern transportkjøretøy (bil, båt, etc.) benyttes, hvilken dokumentasjon må legges frem før ankomst?", "",
  "su1.7",  "q85", 1,  function(.data) { ifelse(.data$`9.11.5`=="Ja",1,0) }, function(.data) { .data$`9.11.5` }, 
  "Er tomme transportkjøretøy (bil, båt, etc.) desinfisert (inni og utenpå) når de forlater lokaliteten?", "",
  "su1.7",  "q86", 1,  function(.data) { ifelse(.data$`9.13`=="Ja",1,ifelse(.data$`9.13`=="Ikke aktuelt, fordi det ikke transporteres fisk til og fra denne lokaliteten",1,0)) }, function(.data) { .data$`9.13` }, 
  "Mottar lokaliteten død fisk fra andre anlegg/lokaliteter?", "",
  "su1.7",  "q87", 1,  function(.data) { ifelse(.data$`14.3`=="Nei",1,0) }, function(.data) { .data$`14.3` }, 
  "Leverer lokaliteten død fisk til andre anlegg/lokaliteter?", "",
  "su1.7",  "q88", 1,  function(.data) { ifelse(.data$`14.4`=="Nei",1,0) }, function(.data) { .data$`14.4` }, 
  "Benytter lokaliteten eksterne selskap for henting av død fisk?", "",
  "su1.7",  "q89", 1,  function(.data) { ifelse(.data$`14.5`=="Nei",1,0) }, function(.data) { .data$`14.5` }, 
  #####
  # INTERNAL BIOSECURITY
  ##### 
  # 8) VACCINATION
  #####
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? IPN", "",
  "su1.8",  "q90", 1,  function(.data) { ifelse(.data$`6.1.1`=="Ikke aktuell",1,ifelse(.data$`6.1.1`=="Liten betydning",0.5,ifelse(.data$`6.1.1`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.1` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? PD", "",
  "su1.8",  "q91", 1,  function(.data) { ifelse(.data$`6.1.2`=="Ikke aktuell",1,ifelse(.data$`6.1.2`=="Liten betydning",0.5,ifelse(.data$`6.1.2`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.2` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? ISA", "",
  "su1.8",  "q92", 1,  function(.data) { ifelse(.data$`6.1.3`=="Ikke aktuell",1,ifelse(.data$`6.1.3`=="Liten betydning",0.5,ifelse(.data$`6.1.3`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.3` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? VIBRIOSE", "",
  "su1.8",  "q93", 1,  function(.data) { ifelse(.data$`6.1.4`=="Ikke aktuell",1,ifelse(.data$`6.1.4`=="Liten betydning",0.5,ifelse(.data$`6.1.4`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.4` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? FURUNKULOSE", "",
  "su1.8",  "q94", 1,  function(.data) { ifelse(.data$`6.1.5`=="Ikke aktuell",1,ifelse(.data$`6.1.5`=="Liten betydning",0.5,ifelse(.data$`6.1.5`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.5` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? Vintersår", "",
  "su1.8",  "q95", 1,  function(.data) { ifelse(.data$`6.1.6`=="Ikke aktuell",1,ifelse(.data$`6.1.6`=="Liten betydning",0.5,ifelse(.data$`6.1.6`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.6` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? Kaldtvannsvibriose", "",
  "su1.8",  "q96", 1,  function(.data) { ifelse(.data$`6.1.7`=="Ikke aktuell",1,ifelse(.data$`6.1.7`=="Liten betydning",0.5,ifelse(.data$`6.1.7`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.7` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? Yersiniose", "",
  "su1.8",  "q97", 1,  function(.data) { ifelse(.data$`6.1.8`=="Ikke aktuell",1,ifelse(.data$`6.1.8`=="Liten betydning",0.5,ifelse(.data$`6.1.8`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.8` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? Flavobakteriose", "",
  "su1.8",  "q98", 1,  function(.data) { ifelse(.data$`6.1.9`=="Ikke aktuell",1,ifelse(.data$`6.1.9`=="Liten betydning",0.5,ifelse(.data$`6.1.9`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.9` }, 
  "Hvilke sykdommer har hatt betydning for tap (dødelighet og tilvekst) på denne lokaliteten de siste 12 mnd? Pasteurellose", "",
  "su1.8",  "q99", 1,  function(.data) { ifelse(.data$`6.1.10`=="Ikke aktuell",1,ifelse(.data$`6.1.10`=="Liten betydning",0.5,ifelse(.data$`6.1.10`=="Moderat betydning",0.5,0))) }, function(.data) { .data$`6.1.10` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? IPN", "",
  "su1.8",  "q100", 1, function(.data) { ifelse(.data$`6.2.1`=="Ja",1,0) }, function(.data) { .data$`6.2.1` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? PD", "",
  "su1.8",  "q101", 1, function(.data) { ifelse(.data$`6.2.2`=="Ja",1,0) }, function(.data) { .data$`6.2.2` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? ISA", "",
  "su1.8",  "q102", 1, function(.data) { ifelse(.data$`6.2.3`=="Ja",1,0) }, function(.data) { .data$`6.2.3` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? VIBRIOSE", "",
  "su1.8",  "q103", 1, function(.data) { ifelse(.data$`6.2.4`=="Ja",1,0) }, function(.data) { .data$`6.2.4` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? FURUNKULOSE", "",
  "su1.8",  "q104", 1, function(.data) { ifelse(.data$`6.2.5`=="Ja",1,0) }, function(.data) { .data$`6.2.5` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? VINTERSAR", "",
  "su1.8",  "q105", 1, function(.data) { ifelse(.data$`6.2.6`=="Ja",1,0) }, function(.data) { .data$`6.2.6` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? Kaldtvannsvibriose", "",
  "su1.8",  "q106", 1, function(.data) { ifelse(.data$`6.2.7`=="Ja",1,0) }, function(.data) { .data$`6.2.7` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? Yersiniose", "",
  "su1.8",  "q107", 1, function(.data) { ifelse(.data$`6.2.8`=="Ja",1,0) }, function(.data) { .data$`6.2.8` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? Flavobakteriose", "",
  "su1.8",  "q108", 1, function(.data) { ifelse(.data$`6.2.9`=="Ja",1,0) }, function(.data) { .data$`6.2.9` }, 
  "Er fisken på lokaliteten vaksinert mot følgende sykdommer? Pasteurellose", "",
  "su1.8",  "q109", 1, function(.data) { ifelse(.data$`6.2.10`=="Ja",1,0) }, function(.data) { .data$`6.2.10` }, 
  "Hvordan utføres vaksinering av fisk på denne lokaliteten?", "",
  "su1.8",  "q110", 1, function(.data) { ifelse(.data$`6.3`=="Maskinelt",1,ifelse(.data$`6.3`=="Ikke aktuelt, det vaksineres ikke fisk på denne lokaliteten",1,0)) }, function(.data) { .data$`6.3` }, 
  "Hvem utfører vaksinering av fisk på denne lokaliteten?", "",
  "su1.8",  "q111", 1, function(.data) { ifelse(.data$`6.4`=="Selskapets egne ansatte",1,ifelse(.data$`6.4`=="Innleid vaksineringspersonell",1,0)) }, function(.data) { .data$`6.4` }, 
  ##### 
  # 9) DISEASE MANAGEMENT
  #####
  "Hvor ofte utføres følgende inspeksjoner i anlegget? Overvåkning av generell adferd hos fisken på lokaliteten", "",
  "su1.9",  "q112", 1, function(.data) { ifelse(.data$`16.1.1`=="Minst to ganger daglig",1,ifelse(.data$`16.1.1`=="Minst en gang daglig",1,ifelse(.data$`16.1.1`=="Minst to ganger i uken",0.5,ifelse(.data$`16.1.1`=="Mindre enn to ganger i uken",0.2,ifelse(.data$`16.1.1`=="Kontinuerlig kameraovervåkning",1,0))))) }, function(.data) { .data$`16.1.1` }, 
  "Hvor ofte utføres følgende inspeksjoner i anlegget? Undersøke svimere og dødfisk for dødsårsak", "",
  "su1.9",  "q113", 1, function(.data) { ifelse(.data$`16.1.2`=="Minst to ganger daglig",1,ifelse(.data$`16.1.2`=="Minst en gang daglig",1,ifelse(.data$`16.1.2`=="Minst to ganger i uken",0.5,ifelse(.data$`16.1.2`=="Mindre enn to ganger i uken",0.2,ifelse(.data$`16.1.2`=="Kontinuerlig kameraovervåkning",1,0))))) }, function(.data) { .data$`16.1.2` }, 
  "Hvor ofte utføres følgende inspeksjoner i anlegget? Overvåkning av merd og not", "",
  "su1.9",  "q114", 1, function(.data) { ifelse(.data$`16.1.3`=="Minst to ganger daglig",1,ifelse(.data$`16.1.3`=="Minst en gang daglig",1,ifelse(.data$`16.1.3`=="Minst to ganger i uken",0.5,ifelse(.data$`16.1.3`=="Mindre enn to ganger i uken",0.2,ifelse(.data$`16.1.3`=="Kontinuerlig kameraovervåkning",1,0))))) }, function(.data) { .data$`16.1.3` }, 
  "Hvor ofte utføres følgende inspeksjoner i anlegget? Overvåkning av fôringsslanger og relaterte utstyr", "",
  "su1.9",  "q115", 1, function(.data) { ifelse(.data$`16.1.4`=="Minst to ganger daglig",1,ifelse(.data$`16.1.4`=="Minst en gang daglig",1,ifelse(.data$`16.1.4`=="Minst to ganger i uken",0.5,ifelse(.data$`16.1.4`=="Mindre enn to ganger i uken",0.2,ifelse(.data$`16.1.4`=="Kontinuerlig kameraovervåkning",1,0))))) }, function(.data) { .data$`16.1.4` }, 
  "Hvor ofte utføres følgende inspeksjoner i anlegget? Overvåkning av fôringsadferd", "",
  "su1.9",  "q116", 1, function(.data) { ifelse(.data$`16.1.5`=="Minst to ganger daglig",1,ifelse(.data$`16.1.5`=="Minst en gang daglig",1,ifelse(.data$`16.1.5`=="Minst to ganger i uken",0.5,ifelse(.data$`16.1.5`=="Mindre enn to ganger i uken",0.2,ifelse(.data$`16.1.5`=="Kontinuerlig kameraovervåkning",1,0))))) }, function(.data) { .data$`16.1.5` }, 
  "Hvor ofte registreres/loggføres død fisk på lokaliteten?", "",
  "su1.9",  "q117", 1, function(.data) { ifelse(.data$`16.3`=="Daglig",1,ifelse(.data$`16.3`=="Ukentlig",0.5,ifelse(.data$`16.3`=="Månedlig",0.2,0))) }, function(.data) { .data$`16.3` }, 
  "Ved registrering av dødfisk, blir dødefisk kategoriset i henhold til dødsårsak? Predatorer (feks, sel, oter, fugler, kannibalisme)", "",
  "su1.9",  "q118", 1, function(.data) { ifelse(.data$`16.4.1`=="Ja",1,0) }, function(.data) { .data$`16.4.1` }, 
  "Ved registrering av dødfisk, blir dødefisk kategoriset i henhold til dødsårsak? Infeksiøse sykdommer", "",
  "su1.9",  "q119", 1, function(.data) { ifelse(.data$`16.4.2`=="Ja",1,0) }, function(.data) { .data$`16.4.2` }, 
  "Ved registrering av dødfisk, blir dødefisk kategoriset i henhold til dødsårsak? Parasitter (f.eks. lakselus)", "",
  "su1.9",  "q120", 1, function(.data) { ifelse(.data$`16.4.3`=="Ja",1,0) }, function(.data) { .data$`16.4.3` }, 
  "Ved registrering av dødfisk, blir dødefisk kategoriset i henhold til dødsårsak? Taperfisk (avmagrede fisk, 'pinner' etc)", "",
  "su1.9",  "q121", 1, function(.data) { ifelse(.data$`16.4.4`=="Ja",1,0) }, function(.data) { .data$`16.4.4` }, 
  "Ved registrering av dødfisk, blir dødefisk kategoriset i henhold til dødsårsak? Produksjonssykdommer", "",
  "su1.9",  "q122", 1, function(.data) { ifelse(.data$`16.4.5`=="Ja",1,0) }, function(.data) { .data$`16.4.5` }, 
  "Fjernes død eller døende fisk daglig?", "",
  "su1.9",  "q123", 1, function(.data) { ifelse(.data$`16.5`=="Ja",1,0) }, function(.data) { .data$`16.5` }, 
  "Undersøkes død eller døende fisk rutinemessig for å finne dødsårsaken?", "",
  "su1.9",  "q124", 1, function(.data) { ifelse(.data$`16.6`=="Ja",1,0) }, function(.data) { .data$`16.6` }, 
  "Gjøres tiltak for å hindre direkte kontakt mellom syk fisk og annen fisk på lokaliteten?", "",
  "su1.9",  "q125", 1, function(.data) { ifelse(.data$`16.7`=="Ja",1,0) }, function(.data) { .data$`16.7` }, 
  "Hvor ofte blir det foretatt helsemessig gjennomgang av all fisk på lokaliteten?", "",
  "su1.9",  "q126", 1, function(.data) { ifelse(.data$`17.1`=="Minst en gang i måneden",1,ifelse(.data$`17.1`=="Minst seks ganger i året",1,ifelse(.data$`17.1`=="Minst fire ganger i året",1,ifelse(.data$`17.1`=="Minst to ganger i året",0.5,ifelse(.data$`17.1`=="Minst en gang i året",0.5,0))))) }, function(.data) { .data$`17.1` }, 
  "Finnes systemer for overvåkning av sykdommer på denne lokaliteten?", "",
  "su1.9",  "q127", 1, function(.data) { ifelse(.data$`17.2`=="Ja",1,0) }, function(.data) { .data$`17.2` }, 
  "Blir det gjennomført diagnostiske undersøkelser for å avdekke smitte/sykdom hos fisken? Ved dødelighet eller adferdsendring uten kjent årsak", "",
  "su1.9",  "q128", 1, function(.data) { ifelse(.data$`17.3.1`=="Ja",1,0) }, function(.data) { .data$`17.3.1` }, 
  "Blir det gjennomført diagnostiske undersøkelser for å avdekke smitte/sykdom hos fisken? Etter mottak av fisk fra annen lokalitet", "",
  "su1.9",  "q129", 1, function(.data) { ifelse(.data$`17.3.2`=="Ja",1,0) }, function(.data) { .data$`17.3.2` }, 
  "Blir det gjennomført diagnostiske undersøkelser for å avdekke smitte/sykdom hos fisken? Ved forsendelse av fisk til annen lokalitet", "",
  "su1.9",  "q130", 1, function(.data) { ifelse(.data$`17.3.3`=="Ja",1,0) }, function(.data) { .data$`17.3.3` }, 
  "Blir det gjennomført diagnostiske undersøkelser for å avdekke smitte/sykdom hos fisken? Rutinemessig; hyppighet av undersøkelsene avhenger av sykdomstype og tid på året.", "",
  "su1.9",  "q131", 1, function(.data) { ifelse(.data$`17.3.4`=="Ja",1,0) }, function(.data) { .data$`17.3.4` }, 
  "Blir det gjennomført diagnostiske undersøkelser for å avdekke smitte/sykdom hos fisken? Hvis det er påvist viktig sykdom ved andre lokaliteter i området", "",
  "su1.9",  "q132", 1, function(.data) { ifelse(.data$`17.3.5`=="Ja",1,0) }, function(.data) { .data$`17.3.5` }, 
  "Blir det gjennomført diagnostiske undersøkelser for å avdekke smitte/sykdom hos fisken? Ved myndighetspålagte undersøkelser", "",
  "su1.9",  "q133", 1, function(.data) { ifelse(.data$`17.3.6`=="Ja",1,0) }, function(.data) { .data$`17.3.6` }, 
  "Når vil utbrudd av sykdom/dødelighet på lokaliteten bli rapportert? Når det er forhøyet dødelighet", "",
  "su1.9",  "q134", 1, function(.data) { ifelse(.data$`17.4.1`=="Ja",1,0) }, function(.data) { .data$`17.4.1` }, 
  "Når vil utbrudd av sykdom/dødelighet på lokaliteten bli rapportert? Når sykdommen er ukjent eller uvanlig.", "",
  "su1.9",  "q135", 1, function(.data) { ifelse(.data$`17.4.2`=="Ja",1,0) }, function(.data) { .data$`17.4.2` }, 
  "Når vil utbrudd av sykdom/dødelighet på lokaliteten bli rapportert? Når sykdomsutbruddet varer lenger enn forventet.", "",
  "su1.9",  "q136", 1, function(.data) { ifelse(.data$`17.4.3`=="Ja",1,0) }, function(.data) { .data$`17.4.3` }, 
  "Når vil utbrudd av sykdom/dødelighet på lokaliteten bli rapportert? Når behandling/medisinering ikke hjelper.", "",
  "su1.9",  "q137", 1, function(.data) { ifelse(.data$`17.4.4`=="Ja",1,0) }, function(.data) { .data$`17.4.4` }, 
  "Når vil utbrudd av sykdom/dødelighet på lokaliteten bli rapportert? Utbrudd som er pålagt å rapportere.", "",
  "su1.9",  "q138", 1, function(.data) { ifelse(.data$`17.4.5`=="Ja",1,0) }, function(.data) { .data$`17.4.5` }, 
  "Blir disse tiltakene gjennomført ved sykdomsutbrudd? Ansatte informes med henvisning til lokalitetensbiosikkerhetsplaner", "",
  "su1.9",  "q139", 1, function(.data) { ifelse(.data$`17.5.1`=="Ja",1,0) }, function(.data) { .data$`17.5.1` }, 
  "Blir disse tiltakene gjennomført ved sykdomsutbrudd? Det innføres midlertidig stans av inntak av ny fisk i anlegget", "",
  "su1.9",  "q140", 1, function(.data) { ifelse(.data$`17.5.2`=="Ja",1,0) }, function(.data) { .data$`17.5.2` }, 
  "Blir disse tiltakene gjennomført ved sykdomsutbrudd? Undersøke vannkvalitet og ernæring", "",
  "su1.9",  "q141", 1, function(.data) { ifelse(.data$`17.5.3`=="Ja",1,0) }, function(.data) { .data$`17.5.3` }, 
  "Blir disse tiltakene gjennomført ved sykdomsutbrudd? Kontakte fiskehelsetjenesten man har avtale med, for prøveuttak og utredning av utbruddet", "",
  "su1.9",  "q142", 1, function(.data) { ifelse(.data$`17.5.4`=="Ja",1,0) }, function(.data) { .data$`17.5.4` }, 
  "Blir disse tiltakene gjennomført ved sykdomsutbrudd? Søke råd hos myndighetene", "",
  "su1.9",  "q143", 1, function(.data) { ifelse(.data$`17.5.5`=="Ja",1,0) }, function(.data) { .data$`17.5.5` }, 
  "Blir disse tiltakene gjennomført ved sykdomsutbrudd? Evaluere eksisterende biosikkerhetstiltak", "",
  "su1.9",  "q144", 1, function(.data) { ifelse(.data$`17.5.6`=="Ja",1,0) }, function(.data) { .data$`17.5.6` }, 
  "Hvem rapporteres sykdomsutbrudd til? Fiskehelsetjeneste man har avtale med", "",
  "su1.9",  "q145", 1, function(.data) { ifelse(.data$`17.6.1`=="Ja",1,ifelse(.data$`17.6.1`=="Av og til",0.5,0)) }, function(.data) { .data$`17.6.1` }, 
  "Hvem rapporteres sykdomsutbrudd til? Mattilsynet", "",
  "su1.9",  "q146", 1, function(.data) { ifelse(.data$`17.6.2`=="Ja",1,ifelse(.data$`17.6.2`=="Av og til",0.5,0)) }, function(.data) { .data$`17.6.2` }, 
  "Hvem rapporteres sykdomsutbrudd til? Til fiskehelseansvarlig i selskapet", "",
  "su1.9",  "q147", 1, function(.data) { ifelse(.data$`17.6.3`=="Ja",1,ifelse(.data$`17.6.3`=="Av og til",0.5,0)) }, function(.data) { .data$`17.6.3` }, 
  "Hvem gjør prøveuttak ved sykdomsutbrudd?", "",
  "su1.9",  "q148", 1, function(.data) { ifelse(.data$`17.7`=="Anleggets eget fiskehelsepersonell",1,ifelse(.data$`17.7`=="Fiskehelsetjeneste anlegget har avtale med",1,0)) }, function(.data) { .data$`17.7` }, 
  "Finnes det en egen beredskapsplan for sykdomsutbrudd og forøket dødelighet på lokaliteten?", "",
  "su1.9",  "q149", 1, function(.data) { ifelse(.data$`17.9`=="Ja",1,0) }, function(.data) { .data$`17.9` }, 
  "Finnes en beredskapsplan for miljøforurensing?", "",
  "su1.9",  "q150", 1, function(.data) { ifelse(.data$`17.10`=="Ja",1,0) }, function(.data) { .data$`17.10` }, 
  "Finnes en beredskapsplan i tilfelle feil på utstyr, feks fôringsutstyr?", "",
  "su1.9",  "q151", 1, function(.data) { ifelse(.data$`17.11`=="Ja",1,0) }, function(.data) { .data$`17.11` }, 
  ##### 
  # 10) REARING MANAGEMENT
  #####
  "Har lokaliteten definerte øvre grense for fisketettehet?", "",
  "su1.10", "q152", 1, function(.data) { ifelse(.data$`8.1`=="Ja",1,0) }, function(.data) { .data$`8.1` }, 
  "Etterstrebes optimal fisketetthet som tiltak for å redusere stress hos fisken?", "",
  "su1.10", "q153", 1, function(.data) { ifelse(.data$`8.2`=="Ja",1,0) }, function(.data) { .data$`8.2` }, 
  "For sjø lokaliteter; Blir det flyttet fisk til eller fra denne lokaliteten etter første sjøsetting?", "",
  "su1.10", "q154", 1, function(.data) { ifelse(.data$`8.3`=="Ja",1,ifelse(.data$`8.3`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`8.3` }, 
  "Har lokaliteten rutiner for å dokumentere uhell ved handtering av fisk?", "",
  "su1.10", "q155", 1, function(.data) { ifelse(.data$`8.4`=="Ja",1,0) }, function(.data) { .data$`8.4` }, 
  "Har lokaliteten rutiner for å dokumentere optimal vannkvalitet?", "",
  "su1.10", "q156", 1, function(.data) { ifelse(.data$`8.5`=="Ja",1,0) }, function(.data) { .data$`8.5` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad. Temperatur", "",
  "su1.10", "q157", 1, function(.data) { ifelse(.data$`8.6.1`=="Daglig",1,ifelse(.data$`8.6.1`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.1` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad. Oksygeninnhold", "",
  "su1.10", "q158", 1, function(.data) { ifelse(.data$`8.6.2`=="Daglig",1,ifelse(.data$`8.6.2`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.2` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad.Total mengde amoniakk", "",
  "su1.10", "q159", 1, function(.data) { ifelse(.data$`8.6.3`=="Daglig",1,ifelse(.data$`8.6.3`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.3` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad. Gassmetning", "",
  "su1.10", "q160", 1, function(.data) { ifelse(.data$`8.6.4`=="Daglig",1,ifelse(.data$`8.6.4`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.4` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad.Karbondioksyd", "",
  "su1.10", "q161", 1, function(.data) { ifelse(.data$`8.6.5`=="Daglig",1,ifelse(.data$`8.6.5`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.5` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad. pH", "",
  "su1.10", "q162", 1, function(.data) { ifelse(.data$`8.6.6`=="Daglig",1,ifelse(.data$`8.6.6`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.6` }, 
  "Hvilke vannkvalitetsparameter blir monitorert/overvåket? Velg alle aktuelle alternativ, med èn markering pr. rad. Vanngjennomstrømningsrate", "",
  "su1.10", "q163", 1, function(.data) { ifelse(.data$`8.6.7`=="Daglig",1,ifelse(.data$`8.6.7`=="Av og til",0.5,0)) }, function(.data) { .data$`8.6.7` }, 
  "Praktiseres 'alt inn-alt ut'-prinsippet på lokaliteten? Med dette menes at ny fisk IKKE inkluderes i eksisterende fiskegrupper (dvs. samme not sjøanlegg eller samme avdeling, settefiskanlegg) i løpet av samme produksjonssyklus", "",
  "su1.10", "q164", 1, function(.data) { ifelse(.data$`8.7`=="Ja",1,0) }, function(.data) { .data$`8.7` }, 
  ##### 
  # 11) FEED MANAGEMENT
  #####
  "Hvor ofte inspiseres lagret fôr?", "",
  "su1.11", "q165", 1, function(.data) { ifelse(.data$`7.1`=="Daglig",1,ifelse(.data$`7.1`=="Minst en gang i uken",0.8,0)) }, function(.data) { .data$`7.1` }, 
  "Ved inspeksjon av lagret fôr, hvilke faktorer undersøkes? (Velg alle aktuelle alternativ)", "",
  "su1.11", "q166", 1, function(.data) { ifelse(.data$`7.2`=="Utløpsdato, Forurensing",1,ifelse(.data$`7.2`=="Utløpsdato",0.5,ifelse(.data$`7.2`=="Forurensing",0.5,0))) }, function(.data) { .data$`7.2` }, 
  "Hvordan lagres fôret?", "",
  "su1.11", "q167", 1, function(.data) { ifelse(.data$`7.3`=="I lukkede beholdere, Kjølig og tørt, Utilgjengelig for skadedyr",1,ifelse(.data$`7.3`=="I lukkede beholdere, Kjølig og tørt",2/3,ifelse(.data$`7.3`=="I lukkede beholdere",1/3,ifelse(.data$`7.3`=="Kjølig og tørt, Utilgjengelig for skadedyr",2/3,ifelse(.data$`7.3`=="Utilgjengelig for skadedyr",1/3,ifelse(.data$`7.3`=="I lukkede beholdere, Utilgjengelig for skadedyr",2/3,ifelse(.data$`7.3`=="Kjølig og tørt",1/3,0))))))) }, function(.data) { .data$`7.3` }, 
  "Hvordan fôres fisken i anlegget på denne lokaliteten? (Velg alle aktuelle alternativ)", "",
  "su1.11", "q168", 1, function(.data) { ifelse(.data$`7.4`=="Helautomatisk fôring",1,0) }, function(.data) { .data$`7.4` }, 
  "Hvor ofte inspiseres fôringen?", "",
  "su1.11", "q169", 1, function(.data) { ifelse(.data$`7.5`=="Hver gang fisken fôres",1,ifelse(.data$`7.5`=="Daglig",1,ifelse(.data$`7.5`=="Minst en gang i uken",0.5,0))) }, function(.data) { .data$`7.5` }, 
  ##### 
  # 12) WASTE MANAGEMENT
  #####
  "Blir død fisk fra lokaliteten lagret i lukkede beholdere eller containere?", "",
  "su1.12", "q170", 1, function(.data) { ifelse(.data$`14.1`=="Ja",1,0) }, function(.data) { .data$`14.1` }, 
  "Benytter lokaliteten vanntette beholdere for død fisk?", "",
  "su1.12", "q171", 1, function(.data) { ifelse(.data$`14.2`=="Ja",1,0) }, function(.data) { .data$`14.2` }, 
  "Hvordan lagres død fisk på lokaliteten?", "",
  "su1.12", "q172", 1, function(.data) { ifelse(.data$`14.6`=="Frosset på -18 eller lavere",1,ifelse(.data$`14.6`=="Oppbevares kjølig (under 4C)",1,ifelse(.data$`14.6`=="Ensilert (ved pH under 4)",1,0))) }, function(.data) { .data$`14.6` }, 
  "Hvor ofte fjernes vanligvis død fisk fra kar/merder?", "",
  "su1.12", "q173", 1, function(.data) { ifelse(.data$`14.7`=="Daglig",1,ifelse(.data$`14.7`=="Minst en gang i uken",0.5,0)) }, function(.data) { .data$`14.7` }, 
  ##### 
  # 13) HARVESTING
  #####
  "Utføres det videreforedling og/eller pakking av produkter på lokaliteten?", "",
  "su1.13", "q174", 1, function(.data) { ifelse(.data$`15.1`=="Nei",1,0) }, function(.data) { .data$`15.1` }, 
  "Ved forsendelse av fisk for videreforedling, kjører transportkjøretøyet direkte til videreforedlingsanlegget eller er det innom andre lokaliteter på veien?", "",
  "su1.13", "q175", 1, function(.data) { ifelse(.data$`15.2`=="Ja (kjører direkte til videreforedlingsanlegget)",1,ifelse(.data$`15.2`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.2` }, 
  "Er det satt i verk tiltak ved slakting, for oppsamling og desinfeksjon av vann og blod? (Eksempelvis tiltak for å forhindre lekkasje fra slaktekasser).", "",
  "su1.13", "q176", 1, function(.data) { ifelse(.data$`15.3`=="Ja",1,ifelse(.data$`15.3`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.3` }, 
  "Blir slakteutstyr vasket og desinfisert og undersøkt for skader, mellom to slaktinger?", "",
  "su1.13", "q177", 1, function(.data) { ifelse(.data$`15.4`=="Ja",1,ifelse(.data$`15.4`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.4` }, 
  "Blir slakteutstyret bare brukt på dette anlegget, og ikke på andre anlegg?", "",
  "su1.13", "q178", 1, function(.data) { ifelse(.data$`15.5`=="Ja",1,ifelse(.data$`15.5`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.5` }, 
  "Når vaskes og desinfiseres slakteutstyr? Før slakting", "",
  "su1.13", "q179", 1, function(.data) { ifelse(.data$`15.6.1`=="Ja",1,ifelse(.data$`15.6.1`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.6.1` }, 
  "Når vaskes og desinfiseres slakteutstyr? Etter slakting", "",
  "su1.13", "q180", 1, function(.data) { ifelse(.data$`15.6.2`=="Ja",1,ifelse(.data$`15.6.2`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.6.2` }, 
  "Når vaskes og desinfiseres slakteutstyr? Bare når det er nødvendig", "",
  "su1.13", "q181", 1, function(.data) { ifelse(.data$`15.6.3`=="Ja",1,ifelse(.data$`15.6.3`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.6.3` }, 
  "For landbaserte anlegg: Blir innredninger (kar, tanker, renner eller lignende) vasket og desinfisert etter at fisken er fjernet?", "",
  "su1.13", "q182", 1, function(.data) { ifelse(.data$`15.7`=="Ja",1,ifelse(.data$`15.7`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.7` }, 
  "For sjølokaliteter: Blir alt utstyr som har vært i kontakt med fisken (feks nøter og lignende) vasket og desinfisert, etter at fisken er fjernet?", "",
  "su1.13", "q183", 1, function(.data) { ifelse(.data$`15.8`=="Ja",1,ifelse(.data$`15.8`=="Ikke aktuelt",1,0)) }, function(.data) { .data$`15.8` }, 
  ##### 
  # 14) EQUIPMENT, CLEANING AND DISINFECTION ONSITE
  #####
  "Hvor ofte rengjøres utstyr som brukes på de ulike vekststadier på lokaliteten (kar, renner, nøter eller lignende)? Velg alle aktuelle alternativ med èn markering pr. rad. Smolt", "",
  "su1.14", "q184", 1, function(.data) { ifelse(.data$`8.10.4`=="Daglig",1,ifelse(.data$`8.10.4`=="Minst en gang i uken",0.5,ifelse(.data$`8.10.4`=="Ikke aktuelt",1,0))) }, function(.data) { .data$`8.10.4` }, 
  "Hvor ofte rengjøres utstyr som brukes på de ulike vekststadier på lokaliteten (kar, renner, nøter eller lignende)? Velg alle aktuelle alternativ med èn markering pr. rad.  Matfisk", "",
  "su1.14", "q185", 1, function(.data) { ifelse(.data$`8.10.5`=="Daglig",1,ifelse(.data$`8.10.5`=="Minst en gang i uken",0.5,ifelse(.data$`8.10.5`=="Ikke aktuelt",1,0))) }, function(.data) { .data$`8.10.5` }, 
  "Hvis utstyr blir benyttet mange ulike steder på lokaliteten, blir utstyret RENGJORT før det flyttes fra ett sted til et annet på lokaliteten?", "",
  "su1.14", "q186", 1, function(.data) { ifelse(.data$`9.3`=="Ja",1,0) }, function(.data) { .data$`9.3` }, 
  "Hvis utstyr blir benyttet mange ulike steder på lokaliteten, blir utstyret DESINFISERT før det flyttes fra ett sted til et annet på lokaliteten?", "",
  "su1.14", "q187", 1, function(.data) { ifelse(.data$`9.4`=="Ja",1,0) }, function(.data) { .data$`9.4` }, 
  "Hvordan rengjøres og desinfiseres utstyr, generelt sett?", "",
  "su1.14", "q188", 1, function(.data) { ifelse(.data$`9.5.1`=="Spyling av utstyret for å fjerne synlig materiale (feks med børster, kraftig/stor slange mm).",0, ifelse(.data$`9.5.1`=="Spyling og vask av utstyret med vaskemiddel",0.5,ifelse(.data$`9.5.1`=="Spyling, vask og desinfeksjon av utstyret",1,0))) }, function(.data) { .data$`9.5.1` }, 
  "Hvordan rengjøres og desinfiseres utstyr, generelt sett?", "",
  "su1.14", "q189", 1, function(.data) { ifelse(.data$`9.5.2`=="Spyling av utstyret for å fjerne synlig materiale (feks med børster, kraftig/stor slange mm).",0, ifelse(.data$`9.5.2`=="Spyling og vask av utstyret med vaskemiddel",0.5,ifelse(.data$`9.5.2`=="Spyling, vask og desinfeksjon av utstyret",1,0))) }, function(.data) { .data$`9.5.2` }, 
  "Hvordan rengjøres og desinfiseres utstyr, generelt sett?", "",
  "su1.14", "q190", 1, function(.data) { ifelse(.data$`9.5.3`=="Spyling av utstyret for å fjerne synlig materiale (feks med børster, kraftig/stor slange mm).",0, ifelse(.data$`9.5.3`=="Spyling og vask av utstyret med vaskemiddel",0.5,ifelse(.data$`9.5.3`=="Spyling, vask og desinfeksjon av utstyret",1,0))) }, function(.data) { .data$`9.5.3` }, 
  "Hvordan rengjøres og desinfiseres utstyr, generelt sett?", "",
  "su1.14", "q191", 1, function(.data) { ifelse(.data$`9.5.4`=="Spyling av utstyret for å fjerne synlig materiale (feks med børster, kraftig/stor slange mm).",0, ifelse(.data$`9.5.4`=="Spyling og vask av utstyret med vaskemiddel",0.5,ifelse(.data$`9.5.4`=="Spyling, vask og desinfeksjon av utstyret",1,0))) }, function(.data) { .data$`9.5.4` }, 
  "Hvordan rengjøres og desinfiseres utstyr, generelt sett?", "",
  "su1.14", "q192", 1, function(.data) { ifelse(.data$`9.5.5`=="Spyling av utstyret for å fjerne synlig materiale (feks med børster, kraftig/stor slange mm).",0, ifelse(.data$`9.5.5`=="Spyling og vask av utstyret med vaskemiddel",0.5,ifelse(.data$`9.5.5`=="Spyling, vask og desinfeksjon av utstyret",1,0))) }, function(.data) { .data$`9.5.5` }, 
  "Hvordan rengjøres og desinfiseres utstyr, generelt sett?", "",
  "su1.14", "q193", 1, function(.data) { ifelse(.data$`9.5.6`=="Spyling av utstyret for å fjerne synlig materiale (feks med børster, kraftig/stor slange mm).",0, ifelse(.data$`9.5.6`=="Spyling og vask av utstyret med vaskemiddel",0.5,ifelse(.data$`9.5.6`=="Spyling, vask og desinfeksjon av utstyret",1,0))) }, function(.data) { .data$`9.5.6` }, 
  "Ved sykdomsutbrudd, benyttes utstyr som kun skal brukes på områder av lokaliteten som er smittet?", "",
  "su1.14", "q194", 1, function(.data) { ifelse(.data$`9.6`=="Ja",1,0) }, function(.data) { .data$`9.6` }, 
  "Blir utstyret vasket (tanker / fartøyer / produksjonslinjer eller lignende) eller lar merdene stå tomme i en lengre periode etter at den syke / døde fisken er fjernet?", "",
  "su1.14", "q195", 1, function(.data) { ifelse(.data$`9.7`=="Ja",1,0) }, function(.data) { .data$`9.7` }, 
  "Hvilken beskyttelses-bekledning må personalet ha på seg, når de arbeider i anlegget?Overall/kjeledress, forkle (engangs- eller ikke-engangs)", "",
  "su1.14", "q196", 1, function(.data) { ifelse(.data$`11.5.1`=="Ja",1,0) }, function(.data) { .data$`11.5.1` }, 
  "Hvilken beskyttelses-bekledning må personalet ha på seg, når de arbeider i anlegget? Fottøy", "",
  "su1.14", "q197", 1, function(.data) { ifelse(.data$`11.5.2`=="Ja",1,0) }, function(.data) { .data$`11.5.2` }, 
  "Hvilken beskyttelses-bekledning må personalet ha på seg, når de arbeider i anlegget? Hansker", "",
  "su1.14", "q198", 1, function(.data) { ifelse(.data$`11.5.3`=="Ja",1,0) }, function(.data) { .data$`11.5.3` }, 
  "Hvor ofte vaskes beskyttelses-bekledningen?", "",
  "su1.14", "q199", 1, function(.data) { ifelse(.data$`11.6`=="Minst en gang daglig",1,ifelse(.data$`11.6`=="Minst en gang i uken",0.5,0)) }, function(.data) { .data$`11.6` }, 
  "Hvor ofte desinfiseres beskyttelses-bekledning?", "",
  "su1.14", "q200", 1, function(.data) { ifelse(.data$`11.7`=="Minst en gang daglig",1,ifelse(.data$`11.7`=="Minst en gang i uken",0.5,0)) }, function(.data) { .data$`11.7` }, 
  "Benyttes spesielle og lett gjenkjennelige klær (feks med fargekoder) for hver av de ulike produksjonsenhetene på samme lokalitet?", "",
  "su1.14", "q201", 1, function(.data) { ifelse(.data$`11.9`=="Ja",1,0) }, function(.data) { .data$`11.9` }, 
  "Finnes egne separate områder, innredninger, fasiliteter, utstyr og personell, som benyttes for håndtering av syk fisk?", "",
  "su1.14", "q202", 1, function(.data) { ifelse(.data$`16.8.1`=="Ja",1,0) }, function(.data) { .data$`16.8.1` }, 
  "Finnes egne separate områder, innredninger, fasiliteter, utstyr og personell, som benyttes for håndtering av syk fisk?", "",
  "su1.14", "q203", 1, function(.data) { ifelse(.data$`16.8.2`=="Ja",1,0) }, function(.data) { .data$`16.8.2` }, 
  "Finnes egne separate områder, innredninger, fasiliteter, utstyr og personell, som benyttes for håndtering av syk fisk?", "",
  "su1.14", "q204", 1, function(.data) { ifelse(.data$`16.8.3`=="Ja",1,0) }, function(.data) { .data$`16.8.3` }, 
  "Hvis det ikke er mulig å benytte separate fasiliteter, utstyr og personell ved håndtering av syk fisk: Undersøkes og håndteres syk fisk til slutt?", "",
  "su1.14", "q205", 1, function(.data) { ifelse(.data$`16.9`=="Ja",1,0) }, function(.data) { .data$`16.9` }, 
  "Vaskes og desinfiseres alt av utstyr, klær, støvler etc, som kommer i kontakt med syk fisk?", "",
  "su1.14", "q206", 1, function(.data) { ifelse(.data$`16.10`=="Ja",1,0) }, function(.data) { .data$`16.10` }, 
  "Skal personale alltid vaske og desinfisere hendene etter kontakt med syk og død fisk?", "",
  "su1.14", "q207", 1, function(.data) { ifelse(.data$`16.11`=="Ja",1,0) }, function(.data) { .data$`16.11` }, 
  ##### 
  # 15) BIOSECURITY PROGRAM AND RECORD KEEPING
  #####
  "Har lokaliteten egen standard prosedyre for biosikkerhet (SOPs)?", "",
  "su1.15", "q208", 1, function(.data) { ifelse(.data$`18.1`=="Ja",1,0) }, function(.data) { .data$`18.1` }, 
  "Hvor ofte får medarbeiderne gjennomgang og opplæring i biosikkerhetsprosedyren (SOP'en)?", "",
  "su1.15", "q209", 1, function(.data) { ifelse(.data$`18.2`=="Minst en gang i året",1, ifelse(.data$`18.2`=="Minst en gang hvert andre år",0.5, ifelse(.data$`18.2`=="Minst en gang hvert tredje år",0.2,0))) }, function(.data) { .data$`18.2` }, 
  "Revideres denne lokaliteten regelmessig vha kvalitetsprogram som feks 'Friends of the Sea', 'GlobalGAP', etc ?", "",
  "su1.15", "q210", 1, function(.data) { ifelse(.data$`18.3`=="Ja",1,0) }, function(.data) { .data$`18.3` }, 
  "Hvor ofte revideres biosikkerhetsprosedyren?", "",
  "su1.15", "q211", 1, function(.data) { ifelse(.data$`18.4`=="Minst en gang i året",1, ifelse(.data$`18.4`=="Minst en gang hvert andre år",0.5, ifelse(.data$`18.4`=="Minst en gang hvert tredje år",0.2,0))) }, function(.data) { .data$`18.4` }, 
  "Registreres data fra følgende deler av virksomheten?", "",
  "su1.15", "q212", 1, function(.data) { ifelse(.data$`18.5.1`=="Ja",1,0) }, function(.data) { .data$`18.5.1` }, 
  "Registreres data fra følgende deler av virksomheten?", "",
  "su1.15", "q213", 1, function(.data) { ifelse(.data$`18.5.2`=="Ja",1,0) }, function(.data) { .data$`18.5.2` }, 
  "Registreres data fra følgende deler av virksomheten?", "",
  "su1.15", "q214", 1, function(.data) { ifelse(.data$`18.5.3`=="Ja",1,0) }, function(.data) { .data$`18.5.3` }, 
  "Registreres data fra følgende deler av virksomheten?", "",
  "su1.15", "q215", 1, function(.data) { ifelse(.data$`18.5.4`=="Ja",1,0) }, function(.data) { .data$`18.5.4` }, 
  "Registreres data fra følgende deler av virksomheten?", "",
  "su1.15", "q216", 1, function(.data) { ifelse(.data$`18.5.5`=="Ja",1,0) }, function(.data) { .data$`18.5.5` }
  #####
)
#####

# Make sure stat_qn is unique
if (dplyr::n_distinct(stat_questions_growout$stat_qn) != nrow(stat_questions_growout)) {
  stop("stat_qn is not unique")
  stat_questions_growout$stat_qn <- paste0("q", seq_len(nrow(stat_questions_growout)))
}

saveRDS(stat_subgroups_total_weights_growout, "input/stat_subgroups_total_weights_growout.Rds")
saveRDS(stat_subgroups_int_ext_weights_growout, "input/stat_subgroups_int_ext_weights_growout.Rds")
saveRDS(stat_subgroups_growout, "input/stat_subgroups_growout.Rds")
saveRDS(stat_questions_growout, "input/stat_questions_growout.Rds")




